In [124]:
import numpy as np
import pandas as pd

In [125]:
df = pd.read_csv('/Users/anikchand/Documents/Sentiment_analysis/IMDB_Dataset.csv')

In [126]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [127]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

## Text cleaning
1. sample 10000 rows
2. remove html tags
3. remove special characters
4. converting every thing to lower case
5. Removing stop words
6. Stemming

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [129]:
df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)

/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_32092/3199577391.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1, 'negative':0}, inplace=True)
/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_32092/3199577391.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent

In [130]:
df.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [131]:
df['review'][5207]

s = 'Well, TiVo recorded this because of Angelina Jolie. It had 2.5 stars. It seemed promising. It went downhill fast.<br /><br />There is much overacting, even from Angelina. She\'s about 20 and playing a 16 year old. There are three characters that are supposed to be Italian. Everyone else is Italian- American. The native Italian accents were good, I thought. The young male lead is cute, my wife says. Everyone else in this movie is a fat Italian woman. Even the men.<br /><br />I should have known that when Dick Van Patten was cast as a randy doctor, that that was a bad sign. The two couples chasing their kids around are like the four Italian Stooges.<br /><br />My wife would not let go of the remote. Hopefully she was not taking makeup, clothing or decorating tips. It was a sick and twisted combination of hideous and garish. It was hidegarishous.<br /><br />Cutting off my left ventricle was not sufficient to distract from the pain of watching this movie. If this movie shows up on your TV, do yourself a favor and ram your head through the TV screen instead. You\'ll be glad you did. The only movie I\'ve ever seen that was worse than this was "Hamburger: The Movie". Or maybe "Deadly Friend".'

In [132]:
import re

clean = re.compile('<.*?>')

re.sub(clean, '', s)

'Well, TiVo recorded this because of Angelina Jolie. It had 2.5 stars. It seemed promising. It went downhill fast.There is much overacting, even from Angelina. She\'s about 20 and playing a 16 year old. There are three characters that are supposed to be Italian. Everyone else is Italian- American. The native Italian accents were good, I thought. The young male lead is cute, my wife says. Everyone else in this movie is a fat Italian woman. Even the men.I should have known that when Dick Van Patten was cast as a randy doctor, that that was a bad sign. The two couples chasing their kids around are like the four Italian Stooges.My wife would not let go of the remote. Hopefully she was not taking makeup, clothing or decorating tips. It was a sick and twisted combination of hideous and garish. It was hidegarishous.Cutting off my left ventricle was not sufficient to distract from the pain of watching this movie. If this movie shows up on your TV, do yourself a favor and ram your head through 

In [133]:
# function to clean html codes

def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [134]:
df['review'] = df['review'].apply(clean_html)

In [135]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [136]:
df['review'] = df['review'].apply(convert_lower)

In [137]:
# to remove special characters

def remove_special(text):
    x = ''
    
    for i in text:
        if i.isalnum():
            x += i
        else:
            x += ' '
    
    return x

In [138]:
remove_special("hjgajhsd5$#34*snjfds(sdhfj[SFj]bsdbf\\sf)")

'hjgajhsd5  34 snjfds sdhfj SFj bsdbf sf '

In [139]:
df['review'] = df['review'].apply(remove_special)

In [140]:
import sys
!{sys.executable} -m pip install nltk


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [141]:
# remove the stop words
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anikchand/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [142]:
from nltk.corpus import stopwords

In [143]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [144]:

def remove_stopwords(text):
    x = []
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    
    y = x[:]
    x.clear()
    return y

In [145]:
df['review'] = df['review'].apply(remove_stopwords)

In [146]:
df

review  sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...          1
1      [wonderful, little, production, filming, techn...          1
2      [thought, wonderful, way, spend, time, hot, su...          1
3      [basically, family, little, boy, jake, thinks,...          0
4      [petter, mattei, love, time, money, visually, ...          1
...                                                  ...        ...
49995  [thought, movie, right, good, job, creative, o...          1
49996  [bad, plot, bad, dialogue, bad, acting, idioti...          0
49997  [catholic, taught, parochial, elementary, scho...          0
49998  [going, disagree, previous, comment, side, mal...          0
49999  [one, expects, star, trek, movies, high, art, ...          0

[50000 rows x 2 columns]

In [147]:
# perform stemming

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [148]:
y = []
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z = y[:]
    y.clear()
    return z

In [149]:
df['review'] = df['review'].apply(stem_words)

In [150]:
df

review  sentiment
0      [one, review, mention, watch, 1, oz, episod, h...          1
1      [wonder, littl, product, film, techniqu, unass...          1
2      [thought, wonder, way, spend, time, hot, summe...          1
3      [basic, famili, littl, boy, jake, think, zombi...          0
4      [petter, mattei, love, time, money, visual, st...          1
...                                                  ...        ...
49995  [thought, movi, right, good, job, creativ, ori...          1
49996  [bad, plot, bad, dialogu, bad, act, idiot, dir...          0
49997  [cathol, taught, parochi, elementari, school, ...          0
49998  [go, disagre, previou, comment, side, maltin, ...          0
49999  [one, expect, star, trek, movi, high, art, fan...          0

[50000 rows x 2 columns]

In [151]:
# join back

def join_back(list_input):
    return ' '.join(list_input)

In [152]:
df['review'] = df['review'].apply(join_back)

In [153]:
df

review  sentiment
0      one review mention watch 1 oz episod hook righ...          1
1      wonder littl product film techniqu unassum old...          1
2      thought wonder way spend time hot summer weeke...          1
3      basic famili littl boy jake think zombi closet...          0
4      petter mattei love time money visual stun film...          1
...                                                  ...        ...
49995  thought movi right good job creativ origin fir...          1
49996  bad plot bad dialogu bad act idiot direct anno...          0
49997  cathol taught parochi elementari school nun ta...          0
49998  go disagre previou comment side maltin one sec...          0
49999  one expect star trek movi high art fan expect ...          0

[50000 rows x 2 columns]

In [154]:
X = df.iloc[:, 0:1].values

In [155]:
X.shape

(50000, 1)

In [156]:
y = df.iloc[:, -1].values

In [179]:
# vactorize

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)

In [ ]:
X = cv.fit_transform(df['review'])

In [183]:
import joblib
joblib.dump(cv, "vectorizer.pkl")

['vectorizer.pkl']

In [184]:
X = X.toarray()

In [185]:
X.shape

(50000, 1000)

In [160]:
X[0].max()

np.int64(4)

In [161]:
y = df.iloc[:, -1].values

In [162]:
y.shape

(50000,)

In [163]:
# train_test_split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [164]:
X_train.shape

(40000, 1000)

In [165]:
y_train

array([1, 0, 0, ..., 0, 0, 1], shape=(40000,))

In [166]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10000, 1000))

In [167]:
y_test

array([0, 1, 1, ..., 1, 0, 1], shape=(10000,))

In [168]:
# model training

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [169]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [170]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

BernoulliNB()

In [171]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)

In [172]:
y_test.shape, y_pred1

((10000,), array([0, 0, 1, ..., 1, 0, 0], shape=(10000,)))

In [173]:
# check accuracy score

from sklearn.metrics import accuracy_score

In [174]:
accuracy_score(y_test, y_pred1), accuracy_score(y_test, y_pred2), accuracy_score(y_test, y_pred3)

(0.7907, 0.835, 0.8394)

In [178]:
import joblib

joblib.dump(clf3, "model.pkl")

['model.pkl']